package com.unisys.trans.logistics.lms.utils.constants;

public enum LoadFileType {
    MIGRATION_GEN_FILE,
    MIGRATION_HOST_FILE,
    STATION_GENERAL_CUSTOMS,
    STATION_GENERAL_LOCATION,
    STATION_SUPPLEMENTAL_AGENCY_HOURS,
    STATION_FACILITY_CONTACT,
    STATION_SUPPLEMENTAL_AGENCY_HOLIDAY,
    STATION_OTHER_SPL_INS,
    STATION_OPERATIONAL_SALES_CONTACTS,
    STATION_HANDLING_DETAILS,
    STATION_FACILITY_ATTRIBUTE;
}
