/* ====================================== */
/* Copyright (c) 2007 Unisys Corporation. */
/*          All rights reserved.          */
/*          UNISYS CONFIDENTIAL           */
/* ====================================== */

package com.unisys.trans.logistics.lms.utils.contract;

import com.unisys.trans.logistics.lms.framework.exception.LMSException;
import com.unisys.trans.logistics.lms.utils.dto.PalletCodeDeleteRequest;
import com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto;
import com.unisys.trans.logistics.lms.utils.dto.PalletCodeFindRequest;
import com.unisys.trans.logistics.lms.utils.dto.PalletCodePersistRequest;
import com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse;

/**
 * Interface of the services offered by <code>PalletCodeService</code>.
 * <p>
 * <code>PalletCodeService</code> handles the maintenance of pallet codes required for a cargo application.
 * The pallet is identified by the system based on the pallet code. It provides create, update, find, and
 * delete services for pallet code details. It provides the following services for <code>PalletCode</code>
 * information.<br>
 * <ul>
 * <code>
 * <li>Creates the PalletCode.
 * <li>Deletes the PalletCode.
 * <li>Finds the PalletCode.
 * <li>Updates the PalletCode.
 * </code>
 * </ul>
 * 
 * @see com.unisys.trans.logistics.lms.utils.dto.PalletCodeDeleteRequest
 * @see com.unisys.trans.logistics.lms.utils.dto.PalletCodeFindRequest
 * @see com.unisys.trans.logistics.lms.utils.dto.PalletCodePersistRequest
 * @see com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse
 */
public interface PalletCodeService {

    /**
     * Creates the pallet code details.
     * <p>
     * <b>Related methods include:</b>
     * <ul>
     * <li>
     * {@link com.unisys.trans.logistics.lms.utils.contract.PalletCodeService#updatePalletCode(PalletCodePersistRequest)
     * updatePalletCode}
     * </ul>
     * <p>
     * <b>Release Notes:</b> <br>
     * <table border="1" cellspacing="0" cellpadding="5" width="80%">
     * <tr>
     * <th align="left">Release</th>
     * <th align="left">Notes</th>
     * </tr>
     * <tr>
     * <td>@Since 1.0</td>
     * <td>&nbsp;</td>
     * </tr>
     * </table>
     * <p>
     * <b>Errors:</b><br>
     * <b>The following Error Codes may be returned :</b>
     * <table border="0" cellspacing="0" cellpadding="5">
     * <code>
     *            <tr>
     *            <td>{@link com.unisys.trans.logistics.lms.utils.constants.MessageConstants#NO_PALLETCODE_ENTITY_FOUND}</td>
     *            <td>The pallet code does not exist.</td>
     *            </tr>
     *            <tr>
     *            <td>{@link com.unisys.trans.logistics.lms.utils.constants.MessageConstants#DUPLICATE_PALLET_CONTOUR_COMBINATION}</td>
     *            <td>The combination of pallet and contour code are duplicated.</td>
     *            </tr>
     *            </code>
     * </table>
     * 
     * @param pPalletCodePersistRequest <code>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodePersistRequest
     *            PalletCodePersistRequest}</code><br>
     *            holds the request object which includes the attributes to create pallet code details.<br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto PalletCodeDto} -
     *            (M)</code><br>
     *            <ul>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setCode palletCode}
     *            - (M)</code><br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setContourCode
     *            contourCode} - (O)</code><br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setDescription
     *            description} - (O)</code><br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setOId oId} - (C)
     *            </code><br>
     *            Prohibited for create operation; auto generated by system<br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setVolume volume} -
     *            (O)</code><br>
     *            </ul>
     *            <p>
     * @return <code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse PalletCodeResponse}
     *         <br> <ul> <li> {@link com.unisys.trans.logistics.lms.framework.dto.AbstractResponse Response
     *         fields} <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse#getPalletCodes
     *         palletCode} - (1,*) <ul> <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto
     *         palletCodeDto} - (1,*) </ul> </ul> </code>
     *         <p>
     * @throws LMSException If the creation of pallet code fails the above mentioned error codes are returned.
     *             Each CodeMessage contains the status code,human readable message and message type.
     */
    PalletCodeResponse createPalletCode(PalletCodePersistRequest pPalletCodePersistRequest)
                throws LMSException;

    /**
     * Deletes the pallet code.
     * <p>
     * Validates the unique identifier and deletes a pallet code information using the unique identifier.
     * <p>
     * <b>Release Notes:</b> <br>
     * <table border="1" cellspacing="0" cellpadding="5" width="80%">
     * <tr>
     * <th align="left">Release</th>
     * <th align="left">Notes</th>
     * </tr>
     * <tr>
     * <td>@Since 1.0</td>
     * <td>&nbsp;</td>
     * </tr>
     * </table>
     * 
     * @param pPalletCodeDeleteRequest <code>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDeleteRequest
     *            PalletCodeDeleteRequest}</code> holds attributes to delete a pallet code.<br>
     *            <code><ul>
     *            <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDeleteRequest#setOId oId} -
     *            (M) </ul> </code>
     *            <p>
     * @return <code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse PalletCodeResponse}
     *         <ul> <li> {@link com.unisys.trans.logistics.lms.framework.dto.AbstractResponse Response fields}
     *         <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse#getPalletCodes
     *         palletCodes} - (1,*) </ul> </code>
     *         <p>
     * @throws LMSException If not able to delete the pallet Code the above mentioned error codes are
     *             returned. Each CodeMessage contains the status code,human readable message and message
     *             type.
     */
    PalletCodeResponse deletePalletCode(PalletCodeDeleteRequest pPalletCodeDeleteRequest) throws LMSException;

    /**
     * Finds the pallet code.
     * <p>
     * <b>Release Notes:</b> <br>
     * <table border="1" cellspacing="0" cellpadding="5" width="80%">
     * <tr>
     * <th align="left">Release</th>
     * <th align="left">Notes</th>
     * </tr>
     * <tr>
     * <td>@Since 1.0</td>
     * <td>&nbsp;</td>
     * </tr>
     * </table>
     * <p>
     * <b>Errors:</b><br>
     * <b>The following Error Codes may be returned :</b>
     * <table border="0" cellspacing="0" cellpadding="5">
     * <code>
     *            <tr>
     *            <td>{@link com.unisys.trans.logistics.lms.utils.constants.MessageConstants#NO_PALLETCODE_ENTITY_FOUND}</td>
     *            <td>The pallet code does not exist.</td>
     *            </tr>
     *            </code>
     * </table>
     * <p>
     * 
     * @param pPalletCode holds the pallet code.
     * @param pContour holds the contour code.
     *            <p>
     * @return <code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto PalletCodeDto} <ul> <li>
     *         {@link com.unisys.trans.logistics.lms.framework.dto.AbstractResponse Response fields} </ul>
     *         </code>
     */
    PalletCodeDto findPalletCode(String pPalletCode, String pContour);

    /**
     * Finds the pallet code details specific to the input code.
     * <p>
     * If a single character pallet code is provided system retrieves all the pallet codes that start with the
     * single character and also all those that follow in alphabetically ascending order. Similarly if a
     * complete pallet code (2 character) is provided, system retrieves all the pallet codes that match this
     * pallet code and those that follow in alphabetically ascending order.
     * <p>
     * When Pallet code is not provided as filter, all pallet codes will be displayed.<br>
     * <p>
     * <b>Release Notes:</b> <br>
     * <table border="1" cellspacing="0" cellpadding="5" width="80%">
     * <tr>
     * <th align="left">Release</th>
     * <th align="left">Notes</th>
     * </tr>
     * <tr>
     * <td>@Since 1.0</td>
     * <td>&nbsp;</td>
     * </tr>
     * </table>
     * <p>
     * 
     * @param pPalletCodeFindRequest <code>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeFindRequest PalletCodeFindRequest}
     *            </code> holds the request object which includes the attributes to find the pallet codes. 
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setCode palletCode}
     *            - (O) </code>
     *            <p>
     * @return <code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse PalletCodeResponse}
     *         <ul> <li> {@link com.unisys.trans.logistics.lms.framework.dto.AbstractResponse Response fields}
     *         <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse#getPalletCodes
     *         palletCodes} - (1,*) </ul> </code>
     *         <p>
     * @throws LMSException If the find operation fails for the given search criteria the above mentioned
     *             error codes are returned. Each CodeMessage contains the status code,human readable message
     *             and message type.
     */
    PalletCodeResponse findPalletCodes(PalletCodeFindRequest pPalletCodeFindRequest) throws LMSException;

    /**
     * Updates the pallet code details.
     * <p>
     * <b>Release Notes:</b> <br>
     * <table border="1" cellspacing="0" cellpadding="5" width="80%">
     * <tr>
     * <th align="left">Release</th>
     * <th align="left">Notes</th>
     * </tr>
     * <tr>
     * <td>@Since 1.0</td>
     * <td>&nbsp;</td>
     * </tr>
     * </table>
     * <p>
     * <b>Errors:</b><br>
     * <b>The following Error Codes may be returned :</b>
     * <table border="0" cellspacing="0" cellpadding="5">
     * <code>
     *            <tr>
     *            <td>{@link com.unisys.trans.logistics.lms.utils.constants.MessageConstants#PALLET_CONTOUR_CANNOT_BE_UPDATED}</td>
     *            <td>Pallet code and contour code cannot be updated.</td>
     *            </tr>
     *            </code>
     * </table>
     * <p>
     * 
     * @param pPalletCodePersistRequest <code>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodePersistRequest
     *            PalletCodePersistRequest}</code><br>
     *            holds the request object thast includes the attributes to update pallet code details.<br>
     *            <li><code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto PalletCodeDto} -
     *            (M) <ul> <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setCode
     *            palletCode} - (M <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setOId
     *            oId} - (M) <li>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setContourCode contourCode} -
     *            (O) <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setDescription
     *            description} - (O) <li>
     *            {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto#setVolume volume} - (O) </ul>
     *            </code>
     *            <p>
     * @return <code> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse PalletCodeResponse}
     *         <ul> <li> {@link com.unisys.trans.logistics.lms.framework.dto.AbstractResponse Response fields}
     *         <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeResponse#getPalletCodes
     *         palletCode} - (1,*) <ul> <li> {@link com.unisys.trans.logistics.lms.utils.dto.PalletCodeDto
     *         palletCodeDto} - (1,*) </ul> </ul> </code>
     *         <p>
     * @throws LMSException If the update of pallet code fails the above mentioned error codes are returned.
     *             Each CodeMessage contains the status code,human readable message and message type.
     */
    PalletCodeResponse updatePalletCode(PalletCodePersistRequest pPalletCodePersistRequest)
                throws LMSException;
}
