//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 01:48:38 PM IST 
//


package com.unisys.trans.logistics.lms.accounting.dto.constants; 


public enum BatchSequenceNumberType {

    PREPAID_AIRWAYBILL("001"),

    COLLECT_AIRWAYBILL("002"),
    
    BILLING_MEMO("003"),
    
    CREDIT_MEMO("004"),
    
    REJECTION_MEMO("005");
    

    /**
     * Attribute to hold the <code>stringValue</code> property.
     */
    private String stringValue;

    /**
     * Attribute to hold the <code>label</code> property.
     */
    private String label;

    BatchSequenceNumberType(final String pBatchSequenceNumberType) {
        this.setStringValue(pBatchSequenceNumberType);
    }

    /**
     * Gets the label.
     * <p>
     * 
     * @return the current value of <code>label</code> property.<br>
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Sets the label.
     * <p>
     * 
     * @param pLabel
     *            the current value of <code>label</code> property.<br>
     */
    public void setLabel(final String pLabel) {
        this.label = pLabel;
    }

    /**
     * Gets the stringValue.
     * <p>
     * 
     * @return the current value of <code>stringValue</code> property.<br>
     */
    public String getStringValue() {
        return this.stringValue;
    }

    /**
     * Sets the stringValue.
     * <p>
     * 
     * @param pStringValue
     *            the current value of <code>stringValue</code> property.<br>
     */
    public void setStringValue(final String pStringValue) {
        this.stringValue = pStringValue;
    }

    /**
     * Default constructor.
     * 
     * @return the current value of <code>name</code> property.<br>
     * 
     */
    public String value() {
        return this.name();
    }
    
    /**
     * Gets the <code>BatchSequenceNumberType</code>.
     * <p>
     * 
     * @param pBatchSequenceNumberType
     *            holds the new value of <code>BatchSequenceNumberType</code>
     *            <p>
     * @return the value of <code>BatchSequenceNumberType</code>
     */
   /* public static BatchSequenceNumberType getBatchSequenceNumberType(
                final String pBatchSequenceNumberType) {

        BatchSequenceNumberType aBatchSequenceNumberType = null;

        for (final BatchSequenceNumberType aType : BatchSequenceNumberType.values()) {

            if (pBatchSequenceNumberType.equals(aType.getStringValue())) {
                aBatchSequenceNumberType = aType;
                break;
            }
        }

        return aBatchSequenceNumberType;

    }
    
    public BigInteger constructBatchSequnceNumber(final String pBatchSequenceNumberType){
    	
    	batchNumber = new BigInteger(pBatchSequenceNumberType);
    	
    	return batchNumber;
    }*/
}
